# Generated by Django 5.0.3 on 2024-04-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('fathers_name', models.CharField(max_length=30)),
                ('permission', models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], default='User', max_length=5)),
                ('birth_date', models.DateField()),
                ('home_address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('auth_token', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
