# Generated by Django 5.0.3 on 2024-04-01 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral', models.DecimalField(decimal_places=0, max_digits=19)),
                ('land_plot_number', models.CharField(max_length=200)),
                ('well', models.BooleanField(default=False)),
                ('electricity', models.BooleanField(default=False)),
                ('fence', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityMeterIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_readings', models.DecimalField(decimal_places=0, max_digits=6)),
                ('emi_serial', models.CharField(max_length=200)),
                ('emi_phases', models.IntegerField(choices=[(1, '1 Фаза'), (3, '3 Фази')])),
                ('land_plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landplots.landplot')),
            ],
        ),
    ]
