# Generated by Django 5.0.3 on 2024-04-08 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_permission'),
        ('landplots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landplot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
