# Generated by Django 5.0.3 on 2024-04-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landplots', '0002_alter_landplot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitymeterindicator',
            name='emi_serial',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='cadastral',
            field=models.DecimalField(decimal_places=0, max_digits=19, unique=True),
        ),
    ]
