# Generated by Django 5.0.3 on 2024-04-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_candidate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
